name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Nova Repository
        uses: actions/checkout@v4
        with:
          repository: "01builders/nova"
          path: "nova"

      - name: Checkout Celestia App Repository
        uses: actions/checkout@v4
        with:
          repository: "01builders/celestia-app"
          path: "celestia-app"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Build Celestia App Binary
        run: |
          cd celestia-app
          # TODO: we can pull from released binaries in the future rather than building.
          make build
          mkdir -p $HOME/bin
          mv build/celestia-appd $HOME/bin/

      - name: Archive Celestia App Binary
        run: |
          cd $HOME/bin
          tar -czvf celestia-app_Linux_x86_64.tar.gz celestia-appd

      - name: Copy Binary to Nova Repo
        run: |
          # remove all binaries in the repo.
          rm nova/appd/celestia-app_*
          # copy over the one we just built.
          cp $HOME/bin/celestia-app_Linux_x86_64.tar.gz nova/appd

      - name: Run Tests
        run: |
          cd nova
          make test-cover